name: Release app

on:
  issue_comment:
    types:
      - "created"

jobs:
  version_bump:
    name: Version Bump
    runs-on: ubuntu-latest
    
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/release' }}
    steps:
    
    - name: Get the SHA
      id: sha
      uses: actions/github-script@v5
      with:
        result-encoding: string
        script: |
          const { owner, repo, number } = context.issue;
          const pr = await github.pulls.get({
            owner,
            repo,
            pull_number: number,
          });
          return pr.data.head.sha

    # - uses: actions/checkout@v2
    #   with:
    #     ref: ${{ steps.sha.outputs.result }}
    - name: Test json stringify
      id: testfnc
      run: |
        SOME_OUTPUT='i am someone special yooo' 
        echo ::set-output name=some_output::"$SOME_OUTPUT"

    - run: echo "::debug::Set the Octocat variable  ===> ${{steps.testfnc.outputs.some_output}}"

    - name: React to comment
      uses: actions/github-script@v4
      with:
        script: |
          const {owner, repo} = context.issue;
          github.reactions.createForIssueComment({
            owner,
            repo,
            comment_id: context.payload.comment.id,
            content: "rocket",
          });

    - name: Message success
      if: ${{ success() }}
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment succeeded! ✅',
          });
    
    - name: Message failure
      if: ${{ failure() }}
      uses: actions/github-script@v4
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Deployment failed! ❌',
          });